/*
* Even Fibonacci numbers
* Problem 2
*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

* * */
console.time('Execution time');
let firstNumber = 1;
let secondNumber = 2;
// Sum = 2 because we have defined second number = 2 which is divisible by 2
let sum = 2;
const max = 4000000;
while (secondNumber <= max) {
  const nextFibonacci = firstNumber + secondNumber;
  firstNumber = secondNumber;
  secondNumber = nextFibonacci;
  if (secondNumber % 2 === 0) {
    sum += secondNumber
  }
}
console.log(`Problem 2 : answer : ${sum}`);
console.timeEnd('Execution time');
